apiVersion: v2
name: clockwork
description: A Helm chart for deploying Clockwork time tracking application to Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - time-tracking
  - productivity
  - clockwork
home: https://github.com/Gargair/clockwork
maintainers:
  - name: Clockwork Team
sources:
  - https://github.com/Gargair/clockwork
